package com.suhang.keyboard.utils

import android.view.KeyEvent

/**
 * Created by 苏杭 on 2017/8/7 20:52.
 */
class KeyMap {
    companion object {
        val keyMap = HashMap<String, Int>()
        const val KEYBOARD = 9999
        init {
            keyMap.put("a", KeyEvent.KEYCODE_A)
            keyMap.put("b", KeyEvent.KEYCODE_B)
            keyMap.put("c", KeyEvent.KEYCODE_C)
            keyMap.put("d", KeyEvent.KEYCODE_D)
            keyMap.put("e", KeyEvent.KEYCODE_E)
            keyMap.put("f", KeyEvent.KEYCODE_F)
            keyMap.put("g", KeyEvent.KEYCODE_G)
            keyMap.put("h", KeyEvent.KEYCODE_H)
            keyMap.put("i", KeyEvent.KEYCODE_I)
            keyMap.put("j", KeyEvent.KEYCODE_J)
            keyMap.put("k", KeyEvent.KEYCODE_K)
            keyMap.put("l", KeyEvent.KEYCODE_L)
            keyMap.put("m", KeyEvent.KEYCODE_M)
            keyMap.put("n", KeyEvent.KEYCODE_N)
            keyMap.put("o", KeyEvent.KEYCODE_O)
            keyMap.put("p", KeyEvent.KEYCODE_P)
            keyMap.put("q", KeyEvent.KEYCODE_Q)
            keyMap.put("r", KeyEvent.KEYCODE_R)
            keyMap.put("s", KeyEvent.KEYCODE_S)
            keyMap.put("t", KeyEvent.KEYCODE_T)
            keyMap.put("u", KeyEvent.KEYCODE_U)
            keyMap.put("v", KeyEvent.KEYCODE_V)
            keyMap.put("w", KeyEvent.KEYCODE_W)
            keyMap.put("x", KeyEvent.KEYCODE_X)
            keyMap.put("y", KeyEvent.KEYCODE_Y)
            keyMap.put("z", KeyEvent.KEYCODE_Z)
            keyMap.put("A", KeyEvent.KEYCODE_A)
            keyMap.put("B", KeyEvent.KEYCODE_B)
            keyMap.put("C", KeyEvent.KEYCODE_C)
            keyMap.put("D", KeyEvent.KEYCODE_D)
            keyMap.put("E", KeyEvent.KEYCODE_E)
            keyMap.put("F", KeyEvent.KEYCODE_F)
            keyMap.put("G", KeyEvent.KEYCODE_G)
            keyMap.put("H", KeyEvent.KEYCODE_H)
            keyMap.put("I", KeyEvent.KEYCODE_I)
            keyMap.put("J", KeyEvent.KEYCODE_J)
            keyMap.put("K", KeyEvent.KEYCODE_K)
            keyMap.put("L", KeyEvent.KEYCODE_L)
            keyMap.put("M", KeyEvent.KEYCODE_M)
            keyMap.put("N", KeyEvent.KEYCODE_N)
            keyMap.put("O", KeyEvent.KEYCODE_O)
            keyMap.put("P", KeyEvent.KEYCODE_P)
            keyMap.put("Q", KeyEvent.KEYCODE_Q)
            keyMap.put("R", KeyEvent.KEYCODE_R)
            keyMap.put("S", KeyEvent.KEYCODE_S)
            keyMap.put("T", KeyEvent.KEYCODE_T)
            keyMap.put("U", KeyEvent.KEYCODE_U)
            keyMap.put("V", KeyEvent.KEYCODE_V)
            keyMap.put("W", KeyEvent.KEYCODE_W)
            keyMap.put("X", KeyEvent.KEYCODE_X)
            keyMap.put("Y", KeyEvent.KEYCODE_Y)
            keyMap.put("Z", KeyEvent.KEYCODE_Z)
            keyMap.put("1", KeyEvent.KEYCODE_1)
            keyMap.put("2", KeyEvent.KEYCODE_2)
            keyMap.put("3", KeyEvent.KEYCODE_3)
            keyMap.put("4", KeyEvent.KEYCODE_4)
            keyMap.put("5", KeyEvent.KEYCODE_5)
            keyMap.put("6", KeyEvent.KEYCODE_6)
            keyMap.put("7", KeyEvent.KEYCODE_7)
            keyMap.put("8", KeyEvent.KEYCODE_8)
            keyMap.put("9", KeyEvent.KEYCODE_9)
            keyMap.put("0", KeyEvent.KEYCODE_0)
            keyMap.put("@", KeyEvent.KEYCODE_AT)
            keyMap.put("#", KeyEvent.KEYCODE_POUND)
            keyMap.put("*", KeyEvent.KEYCODE_STAR)
            keyMap.put("+", KeyEvent.KEYCODE_PLUS)
            keyMap.put("-", KeyEvent.KEYCODE_MINUS)
            keyMap.put("=", KeyEvent.KEYCODE_EQUALS)
            keyMap.put("/", KeyEvent.KEYCODE_BACKSLASH)
            keyMap.put(",", KeyEvent.KEYCODE_COMMA)
            keyMap.put(".", KeyEvent.KEYCODE_PERIOD)
            keyMap.put("[", KeyEvent.KEYCODE_LEFT_BRACKET)
            keyMap.put("]", KeyEvent.KEYCODE_RIGHT_BRACKET)
            keyMap.put(";", KeyEvent.KEYCODE_PERIOD)
            keyMap.put("'", KeyEvent.KEYCODE_PERIOD)
            keyMap.put("SPA", KeyEvent.KEYCODE_SPACE)
            keyMap.put("N1", KeyEvent.KEYCODE_NUMPAD_1)
            keyMap.put("N2", KeyEvent.KEYCODE_NUMPAD_2)
            keyMap.put("N3", KeyEvent.KEYCODE_NUMPAD_3)
            keyMap.put("N4", KeyEvent.KEYCODE_NUMPAD_4)
            keyMap.put("N5", KeyEvent.KEYCODE_NUMPAD_5)
            keyMap.put("N6", KeyEvent.KEYCODE_NUMPAD_6)
            keyMap.put("N7", KeyEvent.KEYCODE_NUMPAD_7)
            keyMap.put("N8", KeyEvent.KEYCODE_NUMPAD_8)
            keyMap.put("N9", KeyEvent.KEYCODE_NUMPAD_9)
            keyMap.put("N0", KeyEvent.KEYCODE_NUMPAD_0)



            keyMap.put("N+", KeyEvent.KEYCODE_NUMPAD_ADD)
            keyMap.put("N-", KeyEvent.KEYCODE_NUMPAD_SUBTRACT)
            keyMap.put("N*", KeyEvent.KEYCODE_NUMPAD_MULTIPLY)
            keyMap.put("N/", KeyEvent.KEYCODE_NUMPAD_DIVIDE)
            keyMap.put("N=", KeyEvent.KEYCODE_NUMPAD_EQUALS)
            keyMap.put("N,", KeyEvent.KEYCODE_NUMPAD_COMMA)
            keyMap.put("N.", KeyEvent.KEYCODE_NUMPAD_DOT)
            keyMap.put("N(", KeyEvent.KEYCODE_NUMPAD_LEFT_PAREN)
            keyMap.put("N)", KeyEvent.KEYCODE_NUMPAD_RIGHT_PAREN)
            keyMap.put("NET", KeyEvent.KEYCODE_NUMPAD_ENTER)
            keyMap.put("F1", KeyEvent.KEYCODE_F1)
            keyMap.put("F2", KeyEvent.KEYCODE_F2)
            keyMap.put("F3", KeyEvent.KEYCODE_F3)
            keyMap.put("F4", KeyEvent.KEYCODE_F4)
            keyMap.put("F5", KeyEvent.KEYCODE_F5)
            keyMap.put("F6", KeyEvent.KEYCODE_F6)
            keyMap.put("F7", KeyEvent.KEYCODE_F7)
            keyMap.put("F8", KeyEvent.KEYCODE_F8)
            keyMap.put("F9", KeyEvent.KEYCODE_F9)
            keyMap.put("F10", KeyEvent.KEYCODE_F10)
            keyMap.put("F11", KeyEvent.KEYCODE_F11)
            keyMap.put("F12", KeyEvent.KEYCODE_F12)


            keyMap.put("ETN", KeyEvent.KEYCODE_ENTER)
            keyMap.put("ESC", KeyEvent.KEYCODE_ESCAPE)
            keyMap.put("↑", KeyEvent.KEYCODE_DPAD_UP)
            keyMap.put("↓", KeyEvent.KEYCODE_DPAD_DOWN)
            keyMap.put("←", KeyEvent.KEYCODE_DPAD_LEFT)
            keyMap.put("→", KeyEvent.KEYCODE_DPAD_RIGHT)
            keyMap.put("DEL", KeyEvent.KEYCODE_DEL)
            keyMap.put("BAC", KeyEvent.KEYCODE_DEL)
            //键盘锁
            keyMap.put("NLC", KeyEvent.KEYCODE_NUM_LOCK)
            keyMap.put("nlc", KeyEvent.KEYCODE_NUM_LOCK)
            //大小写锁
            keyMap.put("CAP", KeyEvent.KEYCODE_CAPS_LOCK)
            keyMap.put("cap", KeyEvent.KEYCODE_CAPS_LOCK)
            keyMap.put("TAB", KeyEvent.KEYCODE_TAB)
            keyMap.put("INS", KeyEvent.KEYCODE_INSERT)
            keyMap.put("PUP", KeyEvent.KEYCODE_PAGE_UP)
            keyMap.put("PDW", KeyEvent.KEYCODE_PAGE_DOWN)
            keyMap.put("HOM", KeyEvent.KEYCODE_MOVE_HOME)
            keyMap.put("END", KeyEvent.KEYCODE_MOVE_END)
            keyMap.put("ALT", KeyEvent.KEYCODE_ALT_LEFT)
            keyMap.put("ALL", KeyEvent.KEYCODE_ALT_LEFT)
            keyMap.put("all", KeyEvent.KEYCODE_ALT_LEFT)
            keyMap.put("SHT", KeyEvent.KEYCODE_SHIFT_LEFT)
            keyMap.put("SHL", KeyEvent.KEYCODE_SHIFT_LEFT)
            keyMap.put("shl", KeyEvent.KEYCODE_SHIFT_LEFT)
            keyMap.put("CTR", KeyEvent.KEYCODE_CTRL_LEFT)
            keyMap.put("CTL", KeyEvent.KEYCODE_CTRL_LEFT)
            keyMap.put("ctl", KeyEvent.KEYCODE_CTRL_LEFT)
            keyMap.put("KEY", KEYBOARD)
        }
    }
}